import Navigation from "@/components/Navigation";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <header className="py-5 px-20 flex gap-6">
          <Navigation />
        </header>
        <main className="flex flex-col items-center justify-between p-8 h-[90vh]">
          {children}
        </main>
      </body>
    </html>
  );
}
